In [83]:
# Cloud HW 3
# Dr. Prevost
# Author: Garrett Hall
# 10/2/2017
# Instructions:
# Use the following variable declaration for the first 10 problems:
q = str('My big car goes fast.')

print (q)

# Use q string for exercises 1-10
print(q[3:6])
print(q[0])
print(q[7:])
print(q[-1])
print(q[:-1])

q_plus2 = [];
for i in range (0,len(q),2):
    q_plus2.append(q[i])
q_plus2= "".join(q_plus2)
print(q_plus2)

q_plus3 = [];
for i in range (0,len(q),3):
    q_plus3.append(q[i])
q_plus3= "".join(q_plus3)
print(q_plus3)

q_plus4 = [];
for i in range (0,len(q),4):
    q_plus4.append(q[i])
q_plus4= "".join(q_plus4)
print(q_plus4)

print(q[::-1])
print("\n")

# Use c for exercises 11-15
import numpy as np
c=np.arange(27).reshape(3,3,3)

print(c[1,:,:])
print("\n")
print(c[0,0,0])
print("\n")
print(c[0,0,:])
print("\n")
print(c[:,2,2])
print("\n")
print(c[1,:,2])


My big car goes fast.
big
M
car goes fast.
.
My big car goes fast
M i a osfs.
Mb ro s
Miaof.
.tsaf seog rac gib yM


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


0


[0 1 2]


[ 8 17 26]


[11 14 17]
